# AWX default user: admin password: 123456 port：80   
# postgres user: awx password: 123456

version: '3.8'
services:

  web:
    image: ansible/awx:latest
    container_name: awx_web
    depends_on:
      - redis
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - "./src/config/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./src/config/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./src/config/nginx.conf:/etc/nginx/nginx.conf"
      - "./src/config/credentials.py:/etc/tower/conf.d/credentials.py"
      - redis-socket:/var/run/redis/
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: ansible/awx:latest
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - "./src/config/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./src/config/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./src/config/nginx.conf:/etc/nginx/nginx.conf"
      - "./src/config/credentials.py:/etc/tower/conf.d/credentials.py"
      - redis-socket:/var/run/redis/
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis-socket:/var/run/redis/
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"

  postgres:
    image: postgres:12
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - postgres_new-data:/var/lib/postgresql/data/pgdata/
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy: 

  nginx:
    image: nginx
    container_name: awx_nginx
    restart: unless-stopped
    depends_on: 
      - redis
      - postgres
    volumes:
      - "./src/config/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "9003:80"

volumes:
  supervisor-socket:
  rsyslog-socket:
  redis-socket:
  postgres_new-data:

networks:
  default:
    name: ${APP_NETWORK}
    external: true
